version: '3.9'

networks:
  backend:
    external: true 

services:
  api-gateway:
    build: .
    container_name: api-gateway
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - backend
