version: '3.9'

networks:
  frontend:
    external: true 

services:
  frontend:
    build: .
    container_name: frontend
    env_file:
      - .env
    ports:
      - "4200:4200"
    networks:
      - backend
