version: '3.9'

networks:
  backend:
    external: true

volumes:
  client-postgres-data:

services:
  # ---------- PostgreSQL ----------
  postgres:
    image: postgres:16
    container_name: ms-client-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: msclient
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 96101204
    volumes:
      - client-postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  # ---------- Client Service ----------
  client-service:
    build: .
    container_name: ms-client
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8086:8086"
    networks:
      - backend