version: '3.9'

networks:
  backend:
    external: true  # Usa a rede compartilhada com o DAC

volumes:
  orchestrator-postgres-data:

services:
  # ---------- PostgreSQL ----------
  postgres:
    image: postgres:16
    container_name: ms-orchestrator-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: saga_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - orchestrator-postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  # ---------- Orchestrator Service ----------
  orchestrator-service:
    build: .
    container_name: ms-orchestrator
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8085:8085"
    networks:
      - backend
