CREATE TABLE manager (
     id BIGSERIAL PRIMARY KEY,
     cpf VARCHAR(14) NOT NULL,
     name VARCHAR(255) NOT NULL,
     email VARCHAR(255) NOT NULL UNIQUE,
     password VARCHAR(255) NOT NULL,
     type VARCHAR(50) NOT NULL
);