CREATE TABLE client (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome      VARCHAR(120)  NOT NULL,
  email     VARCHAR(150)  NOT NULL,
  cpf       VARCHAR(11)   NOT NULL,
  telefone  VARCHAR(20),
  salario   DECIMAL(14,2) NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX ux_client_cpf   ON client (cpf);
CREATE UNIQUE INDEX ux_client_email ON client (email);
