CREATE SCHEMA IF NOT EXISTS client;

CREATE TABLE client.client (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name      VARCHAR(120)  NOT NULL,
  email     VARCHAR(150)  NOT NULL,
  cpf       VARCHAR(11)   NOT NULL,
  phone  VARCHAR(20),
  salary   DECIMAL(14,2) NOT NULL DEFAULT 0,
  status VARCHAR(120) NOT NULL,
  rejectionReason VARCHAR(255),
  street VARCHAR(150),
  number VARCHAR(20), 
  complement VARCHAR(100),  
  neighborhood VARCHAR(100),
  zipCode VARCHAR(20),
  city VARCHAR(100),
  state VARCHAR(50),  
  creationDate TIMESTAMP NOT NULL,
  approvalDate TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX ux_client_cpf   ON client.client (cpf);
CREATE UNIQUE INDEX ux_client_email ON client.client (email);
