version: '3.9'

networks:
  backend:
    external: true

volumes:
  bank-account-postgres-command-data:
  bank-account-postgres-query-data:

services:
  # ---------- PostgreSQL Command DB ----------
  postgres-command:
    image: postgres:16
    container_name: bank-account-postgres-command
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: command_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - bank-account-postgres-command-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  # ---------- PostgreSQL Query DB ----------
  postgres-query:
    image: postgres:16
    container_name: bank-account-postgres-query
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: query_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - bank-account-postgres-query-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  # ---------- Bank Account Service ----------
  bank-account-service:
    build: .
    container_name: ms-bank-account
    depends_on:
      - postgres-command
      - postgres-query
    env_file:
      - .env
    ports:
      - "8081:8081"
    networks:
      - backend
