version: '3.9'

networks:
  backend:
    external: true

volumes:
  pgdata1:
  pgdata2:

services:
  postgres1:
    image: postgres:15
    container_name: postgres1
    environment:
      POSTGRES_DB: command_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5431:5432"
    volumes:
      - pgdata1:/var/lib/postgresql/data
    networks:
      - backend

  postgres2:
    image: postgres:15
    container_name: postgres2
    environment:
      POSTGRES_DB: query_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
    networks:
      - backend

  bank-account-service:
    build: .
    container_name: ms-bank-account
    depends_on:
      - postgres1
      - postgres2
    env_file:
      - .env
    ports:
      - "8082:8082"
    networks:
      - backend
