version: '3.8'

services:
  postgres1:
    image: postgres:16
    container_name: postgres1
    environment:
      POSTGRES_DB: command_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5431:5432"
    volumes:
      - pgdata1:/var/lib/postgresql/data

  postgres2:
    image: postgres:16
    container_name: postgres2
    environment:
      POSTGRES_DB: query_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta para conexão dos serviços
      - "15672:15672" # Porta para acessar o painel de gerenciamento (UI)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  springapp:
    build: .
    container_name: springapp
    depends_on:
      - postgres1
      - postgres2
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_COMMAND_JDBC_URL: jdbc:postgresql://postgres1:5432/command_db
      SPRING_DATASOURCE_COMMAND_USERNAME: postgres
      SPRING_DATASOURCE_COMMAND_PASSWORD: admin
      SPRING_DATASOURCE_QUERY_JDBC_URL: jdbc:postgresql://postgres2:5432/query_db
      SPRING_DATASOURCE_QUERY_USERNAME: postgres
      SPRING_DATASOURCE_QUERY_PASSWORD: admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

volumes:
  pgdata1:
  pgdata2:
